__author__ = 'Konstantin Glazyrin'

from PyQt4 import Qwt5, QtGui, Qt

# Symbol classes
Ellipse = Qwt5.QwtSymbol.Ellipse			# Circle,
Rect = Qwt5.QwtSymbol.Rect			        #Square,
Diamond = Qwt5.QwtSymbol.Diamond			#Diamond,
Triangle = Qwt5.QwtSymbol.Triangle			#Triangle,
DTriangle = Qwt5.QwtSymbol.DTriangle		#Down Triangle,
UTriangle = Qwt5.QwtSymbol.UTriangle		#Up triangle,
LTriangle = Qwt5.QwtSymbol.LTriangle		#Left Triangle,
RTriangle = Qwt5.QwtSymbol.RTriangle		#Right Triangle,
Cross = Qwt5.QwtSymbol.Cross			    #Cross,
XCross = Qwt5.QwtSymbol.XCross			    #XCross,
HLine = Qwt5.QwtSymbol.HLine			    #Horizontal line,
VLine = Qwt5.QwtSymbol.VLine			    #Vertical line,
Star1 = Qwt5.QwtSymbol.Star1			    #Star1,
Star2 = Qwt5.QwtSymbol.Star2			    #Star2,
Hexagon = Qwt5.QwtSymbol.Hexagon			#Hexagon

# Font Classes
FONT_LIGHT = Qt.QFont.Light
FONT_NORMAL = Qt.QFont.Normal
FONT_DEMIBOLD = Qt.QFont.DemiBold
FONT_BOLD = Qt.QFont.Bold
FONT_BLACK = Qt.QFont.Black

# Pen line styles
LINE_SOLID = Qt.Qt.SolidLine
LINE_DASH = Qt.Qt.DashLine
LINE_DOT = Qt.Qt.DotLine
LINE_DASHDOT = Qt.Qt.DashDotLine
LINE_DASHDOTDOT = Qt.Qt.DashDotDotLine

# colors according to http://www.w3.org/TR/SVG/types.html#ColorKeywords
ALICEBLUE = QtGui.QColor('aliceblue')
ANTIQUEWHITE = QtGui.QColor('antiquewhite')
AQUA = QtGui.QColor('aqua')
AQUAMARINE = QtGui.QColor('aquamarine')
AZURE = QtGui.QColor('azure')
BEIGE = QtGui.QColor('beige')
BISQUE = QtGui.QColor('bisque')
BLACK = QtGui.QColor('black')
BLANCHEDALMOND = QtGui.QColor('blanchedalmond')
BLUE = QtGui.QColor('blue')
BLUEVIOLET = QtGui.QColor('blueviolet')
BROWN = QtGui.QColor('brown')
BURLYWOOD = QtGui.QColor('burlywood')
CADETBLUE = QtGui.QColor('cadetblue')
CHARTREUSE = QtGui.QColor('chartreuse')
CHOCOLATE = QtGui.QColor('chocolate')
CORAL = QtGui.QColor('coral')
CORNFLOWERBLUE = QtGui.QColor('cornflowerblue')
CORNSILK = QtGui.QColor('cornsilk')
CRIMSON = QtGui.QColor('crimson')
CYAN = QtGui.QColor('cyan')
DARKBLUE = QtGui.QColor('darkblue')
DARKCYAN = QtGui.QColor('darkcyan')
DARKGOLDENROD = QtGui.QColor('darkgoldenrod')
DARKGRAY = QtGui.QColor('darkgray')
DARKGREEN = QtGui.QColor('darkgreen')
DARKGREY = QtGui.QColor('darkgrey')
DARKKHAKI = QtGui.QColor('darkkhaki')
DARKMAGENTA = QtGui.QColor('darkmagenta')
DARKOLIVEGREEN = QtGui.QColor('darkolivegreen')
DARKORANGE = QtGui.QColor('darkorange')
DARKORCHID = QtGui.QColor('darkorchid')
DARKRED = QtGui.QColor('darkred')
DARKSALMON = QtGui.QColor('darksalmon')
DARKSEAGREEN = QtGui.QColor('darkseagreen')
DARKSLATEBLUE = QtGui.QColor('darkslateblue')
DARKSLATEGRAY = QtGui.QColor('darkslategray')
DARKSLATEGREY = QtGui.QColor('darkslategrey')
DARKTURQUOISE = QtGui.QColor('darkturquoise')
DARKVIOLET = QtGui.QColor('darkviolet')
DEEPPINK = QtGui.QColor('deeppink')
DEEPSKYBLUE = QtGui.QColor('deepskyblue')
DIMGRAY = QtGui.QColor('dimgray')
DIMGREY = QtGui.QColor('dimgrey')
DODGERBLUE = QtGui.QColor('dodgerblue')
FIREBRICK = QtGui.QColor('firebrick')
FLORALWHITE = QtGui.QColor('floralwhite')
FORESTGREEN = QtGui.QColor('forestgreen')
FUCHSIA = QtGui.QColor('fuchsia')
GAINSBORO = QtGui.QColor('gainsboro')
GHOSTWHITE = QtGui.QColor('ghostwhite')
GOLD = QtGui.QColor('gold')
GOLDENROD = QtGui.QColor('goldenrod')
GRAY = QtGui.QColor('gray')
GREY = QtGui.QColor('grey')
GREEN = QtGui.QColor('green')
GREENYELLOW = QtGui.QColor('greenyellow')
HONEYDEW = QtGui.QColor('honeydew')
HOTPINK = QtGui.QColor('hotpink')
INDIANRED = QtGui.QColor('indianred')
INDIGO = QtGui.QColor('indigo')
IVORY = QtGui.QColor('ivory')
KHAKI = QtGui.QColor('khaki')
LAVENDER = QtGui.QColor('lavender')
LAVENDERBLUSH = QtGui.QColor('lavenderblush')
LAWNGREEN = QtGui.QColor('lawngreen')
LEMONCHIFFON = QtGui.QColor('lemonchiffon')
LIGHTBLUE = QtGui.QColor('lightblue')
LIGHTCORAL = QtGui.QColor('lightcoral')
LIGHTCYAN = QtGui.QColor('lightcyan')
LIGHTGOLDENRODYELLOW = QtGui.QColor('lightgoldenrodyellow')
LIGHTGRAY = QtGui.QColor('lightgray')
LIGHTGREEN = QtGui.QColor('lightgreen')
LIGHTGREY = QtGui.QColor('lightgrey')
LIGHTPINK = QtGui.QColor('lightpink')
LIGHTSALMON = QtGui.QColor('lightsalmon')
LIGHTSEAGREEN = QtGui.QColor('lightseagreen')
LIGHTSKYBLUE = QtGui.QColor('lightskyblue')
LIGHTSLATEGRAY = QtGui.QColor('lightslategray')
LIGHTSLATEGREY = QtGui.QColor('lightslategrey')
LIGHTSTEELBLUE = QtGui.QColor('lightsteelblue')
LIGHTYELLOW = QtGui.QColor('lightyellow')
LIME = QtGui.QColor('lime')
LIMEGREEN = QtGui.QColor('limegreen')
LINEN = QtGui.QColor('linen')
MAGENTA = QtGui.QColor('magenta')
MAROON = QtGui.QColor('maroon')
MEDIUMAQUAMARINE = QtGui.QColor('mediumaquamarine')
MEDIUMBLUE = QtGui.QColor('mediumblue')
MEDIUMORCHID = QtGui.QColor('mediumorchid')
MEDIUMPURPLE = QtGui.QColor('mediumpurple')
MEDIUMSEAGREEN = QtGui.QColor('mediumseagreen')
MEDIUMSLATEBLUE = QtGui.QColor('mediumslateblue')
MEDIUMSPRINGGREEN = QtGui.QColor('mediumspringgreen')
MEDIUMTURQUOISE = QtGui.QColor('mediumturquoise')
MEDIUMVIOLETRED = QtGui.QColor('mediumvioletred')
MIDNIGHTBLUE = QtGui.QColor('midnightblue')
MINTCREAM = QtGui.QColor('mintcream')
MISTYROSE = QtGui.QColor('mistyrose')
MOCCASIN = QtGui.QColor('moccasin')
NAVAJOWHITE = QtGui.QColor('navajowhite')
NAVY = QtGui.QColor('navy')
OLDLACE = QtGui.QColor('oldlace')
OLIVE = QtGui.QColor('olive')
OLIVEDRAB = QtGui.QColor('olivedrab')
ORANGE = QtGui.QColor('orange')
ORANGERED = QtGui.QColor('orangered')
ORCHID = QtGui.QColor('orchid')
PALEGOLDENROD = QtGui.QColor('palegoldenrod')
PALEGREEN = QtGui.QColor('palegreen')
PALETURQUOISE = QtGui.QColor('paleturquoise')
PALEVIOLETRED = QtGui.QColor('palevioletred')
PAPAYAWHIP = QtGui.QColor('papayawhip')
PEACHPUFF = QtGui.QColor('peachpuff')
PERU = QtGui.QColor('peru')
PINK = QtGui.QColor('pink')
PLUM = QtGui.QColor('plum')
POWDERBLUE = QtGui.QColor('powderblue')
PURPLE = QtGui.QColor('purple')
RED = QtGui.QColor('red')
ROSYBROWN = QtGui.QColor('rosybrown')
ROYALBLUE = QtGui.QColor('royalblue')
SADDLEBROWN = QtGui.QColor('saddlebrown')
SALMON = QtGui.QColor('salmon')
SANDYBROWN = QtGui.QColor('sandybrown')
SEAGREEN = QtGui.QColor('seagreen')
SEASHELL = QtGui.QColor('seashell')
SIENNA = QtGui.QColor('sienna')
SILVER = QtGui.QColor('silver')
SKYBLUE = QtGui.QColor('skyblue')
SLATEBLUE = QtGui.QColor('slateblue')
SLATEGRAY = QtGui.QColor('slategray')
SLATEGREY = QtGui.QColor('slategrey')
SNOW = QtGui.QColor('snow')
SPRINGGREEN = QtGui.QColor('springgreen')
STEELBLUE = QtGui.QColor('steelblue')
TAN = QtGui.QColor('tan')
TEAL = QtGui.QColor('teal')
THISTLE = QtGui.QColor('thistle')
TOMATO = QtGui.QColor('tomato')
TURQUOISE = QtGui.QColor('turquoise')
VIOLET = QtGui.QColor('violet')
WHEAT = QtGui.QColor('wheat')
WHITE = QtGui.QColor('white')
WHITESMOKE = QtGui.QColor('whitesmoke')
YELLOW = QtGui.QColor('yellow')
YELLOWGREEN = QtGui.QColor('yellowgreen')