__author__ = 'Konstantin Glazyrin'

KEYPROFILE_NAME = 'NAME'
KEYPROFILE_DOORS = 'DOORS'

# format for Motor representation
KEYPROFILE_MOTORFORMAT = 'MOTORFORMAT'

# scan view specific
KEYPROFILE_COLNUMBER = 'COLUMNNUMBER'

# plot - background, grid, fonts
KEYPROFILE_TTAXISFONT = 'TTAXISFONT'
KEYPROFILE_TTBACKGROUND = 'TTBACKGROUND'
KEYPROFILE_TTGRID = 'TTGRID'
KEYPROFILE_TTAXISLABELFONT = 'TTAXISLABELFONT'

# curve specific
KEYPROFILE_CURVE = 'CURVE'

# markers
KEYPROFILE_POINTMARKER = 'POINTMARKER'
KEYPROFILE_POSITIONMARKER = 'POSITIONMARKER'
KEYPROFILE_MOTORMARKER = 'MOTORMARKER'

# timescan specific
KEYPROFILE_TIMESCAN = 'MOTORSTIMESCAN'
KEYPROFILE_TIMESCANPOINTS = 'MOTORSTIMESCANPOINTS'