__author__ = 'p02user'

# a mus to avoid stupid things on reimport
from PyQt4.Qt import Qt as BASE

# Toggling TT plot position selecting modes
SHORTCUT_TOGGLEPOSITION = BASE.Key_1
SHORTCUT_TOGGLEPOINT = BASE.Key_2
SHORTCUT_TOGGLEZOOM = BASE.Key_3

# Autoscale button
SHORTCUT_AUTOSCALE = (BASE.Key_Escape, BASE.Key_A)

# moving markers in TT plot window
SHORTCUT_CLEARMARKER = BASE.Key_Delete

SHORTCUT_MOVELEFT = (BASE.Key_Left)
SHORTCUT_MOVERIGHT = (BASE.Key_Right)

# one could also use a string 'Ctrl+4'
SHORTCUT_JUMPLEFT = (BASE.ALT+BASE.Key_Left)
SHORTCUT_JUMPRIGHT = (BASE.ALT+BASE.Key_Right)

SHORTCUT_YMAX = BASE.Key_Home
SHORTCUT_YMIN = BASE.Key_End

SHORTCUT_XMAX = (BASE.Key_PageUp, BASE.Key_7)
SHORTCUT_XMIN = (BASE.Key_PageDown, BASE.Key_9)

SHORTCUT_XLEFTEDGE = BASE.Key_BracketLeft
SHORTCUT_XRIGHTEDGE = BASE.Key_BracketRight

SHORTCUT_CENTERDERIVATIVE = BASE.Key_5
SHORTCUT_CENTERDERIVATIVENOISY = BASE.ALT+BASE.Key_5
SHORTCUT_CENTERCMS = BASE.Key_8
SHORTCUT_CENTERNEGATIVECMS = BASE.ALT+BASE.Key_8

SHORTCUT_CENTERBETWEENCLICKS = (BASE.Key_C)

