# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_window.ui'
#
# Created: Thu May 28 17:53:51 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(812, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.control = QtGui.QWidget(self.centralwidget)
        self.control.setObjectName(_fromUtf8("control"))
        self.gridLayout_4 = QtGui.QGridLayout(self.control)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 5, 1, 1)
        self.motor_selection = QtGui.QComboBox(self.control)
        self.motor_selection.setMinimumSize(QtCore.QSize(150, 0))
        self.motor_selection.setObjectName(_fromUtf8("motor_selection"))
        self.gridLayout_4.addWidget(self.motor_selection, 1, 1, 1, 1)
        self.lbl_position = QtGui.QLineEdit(self.control)
        self.lbl_position.setEnabled(True)
        self.lbl_position.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_position.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lbl_position.setStyleSheet(_fromUtf8("QLineEdit {background-color: #eee; border: 2px solid #ccc;}"))
        self.lbl_position.setText(_fromUtf8(""))
        self.lbl_position.setReadOnly(True)
        self.lbl_position.setObjectName(_fromUtf8("lbl_position"))
        self.gridLayout_4.addWidget(self.lbl_position, 1, 3, 1, 1)
        self.label = QtGui.QLabel(self.control)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.stack_home = QtGui.QPushButton(self.control)
        self.stack_home.setObjectName(_fromUtf8("stack_home"))
        self.gridLayout_4.addWidget(self.stack_home, 1, 7, 1, 1)
        self.stack_left = QtGui.QPushButton(self.control)
        self.stack_left.setObjectName(_fromUtf8("stack_left"))
        self.gridLayout_4.addWidget(self.stack_left, 1, 6, 1, 1)
        self.go_position = QtGui.QPushButton(self.control)
        self.go_position.setEnabled(False)
        self.go_position.setObjectName(_fromUtf8("go_position"))
        self.gridLayout_4.addWidget(self.go_position, 1, 2, 1, 1)
        self.stack_right = QtGui.QPushButton(self.control)
        self.stack_right.setObjectName(_fromUtf8("stack_right"))
        self.gridLayout_4.addWidget(self.stack_right, 1, 8, 1, 1)
        self.update_env = QtGui.QPushButton(self.control)
        self.update_env.setObjectName(_fromUtf8("update_env"))
        self.gridLayout_4.addWidget(self.update_env, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.control, 1, 0, 1, 1)
        self.graphs = QtGui.QStackedWidget(self.centralwidget)
        self.graphs.setObjectName(_fromUtf8("graphs"))
        self.scan_page = QtGui.QWidget()
        self.scan_page.setObjectName(_fromUtf8("scan_page"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scan_page)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.graphs.addWidget(self.scan_page)
        self.view_page = QtGui.QWidget()
        self.view_page.setObjectName(_fromUtf8("view_page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.view_page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.graphs.addWidget(self.view_page)
        self.gridLayout.addWidget(self.graphs, 2, 0, 1, 1)
        self.motor_view = QtGui.QWidget(self.centralwidget)
        self.motor_view.setStyleSheet(_fromUtf8("QWidget#motor_view {background-color: #c0eec0}"))
        self.motor_view.setObjectName(_fromUtf8("motor_view"))
        self.gridLayout_5 = QtGui.QGridLayout(self.motor_view)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout.addWidget(self.motor_view, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(2, 50)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDoors = QtGui.QMenu(self.menubar)
        self.menuDoors.setObjectName(_fromUtf8("menuDoors"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuDoors.menuAction())

        self.retranslateUi(MainWindow)
        self.graphs.setCurrentIndex(1)
        QtCore.QObject.connect(self.stack_right, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.action_right_stack)
        QtCore.QObject.connect(self.stack_left, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.action_left_stack)
        QtCore.QObject.connect(self.go_position, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.action_position)
        QtCore.QObject.connect(self.stack_home, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.action_home_stack)
        QtCore.QObject.connect(self.update_env, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.action_update_environment)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.motor_selection, self.go_position)
        MainWindow.setTabOrder(self.go_position, self.lbl_position)
        MainWindow.setTabOrder(self.lbl_position, self.update_env)
        MainWindow.setTabOrder(self.update_env, self.stack_left)
        MainWindow.setTabOrder(self.stack_left, self.stack_home)
        MainWindow.setTabOrder(self.stack_home, self.stack_right)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ScanTracker", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Motor: ", None, QtGui.QApplication.UnicodeUTF8))
        self.stack_home.setText(QtGui.QApplication.translate("MainWindow", "&Home", None, QtGui.QApplication.UnicodeUTF8))
        self.stack_left.setText(QtGui.QApplication.translate("MainWindow", "&Left", None, QtGui.QApplication.UnicodeUTF8))
        self.go_position.setText(QtGui.QApplication.translate("MainWindow", "&Go", None, QtGui.QApplication.UnicodeUTF8))
        self.stack_right.setText(QtGui.QApplication.translate("MainWindow", "&Right", None, QtGui.QApplication.UnicodeUTF8))
        self.update_env.setToolTip(QtGui.QApplication.translate("MainWindow", "Pass position to Macro Server", None, QtGui.QApplication.UnicodeUTF8))
        self.update_env.setText(QtGui.QApplication.translate("MainWindow", "to MS", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDoors.setTitle(QtGui.QApplication.translate("MainWindow", "Active Doors", None, QtGui.QApplication.UnicodeUTF8))

